apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  clusterResourceWhitelist: [{ group: '*', kind: '*' }]
  description: The default Argo-CD project.
  destinations: [{ server: '*', namespace: '*' }]
  sourceRepos: ['*']
